console.log(Math.round(7.5));
console.log(Math.round(7.4));
console.log(Math.floor(7.9));
console.log(Math.ceil(7.1));
console.log(Math.abs(-42));
console.log(Math.abs(42));
console.log(Math.max(1, 5, 3, 9, 2)); 
console.log(Math.min(1, 5, 3, 9, 2));
console.log(Math.pow(2, 8));
console.log(Math.sqrt(144));